---
title: "Research"
---

## Peer-reviewed articles

- Johnson, K.E., Pasco, R., **Woody, S.**, Lachmann, M., Johnson-Leon, M., Bhavnani, D., Klima, J., Paltiel, A.D., Fox, S.J. and Meyers, L.A., 2023. Optimizing COVID-19 testing strategies on college campuses: Evaluation of the health and economic costs. PLoS Computational Biology, 19(12). [[journal](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011715)]

- **S. Woody**, O.H.M Padilla and J.G. Scott. "Optimal post-selection
  inference for sparse signals: a nonparametric empirical-Bayes
  approach." _Biometrika_. 2022. [[journal][saFAB biometrika]] [[arXiv preprint][saFAB paper]] [[code][saFABcode]].

- Fox, S.J., Lachmann, M., Tec, M., Pasco, R., **Woody, S**., Du, Z., Wang, X., Ingle, T.A., Javan, E., Dahan, M. and Gaither, K., 2022. Real-time pandemic surveillance using hospital admissions and mobility data. _Proceedings of the National Academy of Sciences_, 119(7). [[journal][foxpnas]]

- Johnson, K. E., **Woody, S.**, Lachmann, M., Fox, S. J., Klima, J., Hines, T. S., & Meyers, L. A. (2021). Real-Time projections of SARS-CoV-2 B.1.1.7 variant in a university setting, Texas, USA. _Emerging Infectious Diseases_, 27(12), 3188. [[journal](https://pmc.ncbi.nlm.nih.gov/articles/PMC8632165/)]

- **S. Woody**, C.M. Carvalho and J.S. Murray. "Model interpretation
  through lower-dimensional posterior summarization." _Journal of
  Computational and Graphical Statistics_. 2020.  [[arXiv
  preprint][model projections]] [[journal][jcgs2020-07]]
  [[code][ASTRAL code]].

- C.L. Feider, **S. Woody**, S. Ledet, J. Zhang, K. Sebastian,
  M.T. Breen, and L.S. Eberlin.  "Molecular Imaging of Endometriosis
  Tissues using Desorption Electrospray Ionization Mass Spectrometry."
  *Scientific Reports*. 2019. [[journal][endo]].


- R. J. DeHoog, J. Zhang, E. Alore, J.Q. Lin, W. Yu, **S. Woody**,
  C. Almendariz, M. Lin, A. Engelsman, S.B. Sidhu, R.J. Tibshirani,
  J. Suliburk, and L.S. Eberlin.  "Preoperative Metabolic
  Classification of Thyroid Nodules using Mass Spectrometry Imaging of
  Fine Needle Aspiration Biopsies." *PNAS*. 2019. [[journal][PNAS thyroid]]

- C. Carvalho, A. Feller, J. Murray, **S. Woody**, and
  D. Yeager. "Assessing Treatment Effect Variation in Observational
  Studies: Results from a Data Challenge." *Observational
  Studies*. 2019. [[journal][obs-studies-journal]] [[arXiv
  preprint][obs-studies-arXiv]]. 

## Pre-prints and papers under review

- **Spencer Woody**, Carlos M. Carvalho, P. Richard Hahn, and Jared
  S. Murray. "Estimating heterogeneous effects of continuous exposures
  using Bayesian tree ensembles: revisiting the impact of abortion
  rates on crime." [[arXiv preprint][cbcf]].

- **Spencer Woody**, Mauricio Garcia Tec, Maytal Dahan, Kelly Gaither,
  Spencer Fox, Lauren Ancel Meyers, and James G. Scott.  “Projections
  for first-wave COVID-19 deaths across the US using social-distancing
  measures derived from mobile phones.”  [[medRxiv
  preprint](https://doi.org/10.1101/2020.04.16.20068163)]. 


- **S. Woody**, C.M. Carvalho and J.S. Murray. "Bayesian inference for
    treatment effects under nested subsets of controls." 2020.
    [[arXiv preprint][causal dss]].

- **S. Woody**, N. Ghaffari, and L. Hund.  "Bayesian Model Calibration
  for Extrapolative Prediction via Gibbs Posteriors." 2019.  [[arXiv
  preprint][UQ paper]].
  


  
[jcgs2020-07]: https://doi.org/10.1080/10618600.2020.1796684
[cbcf]: https://arxiv.org/abs/2007.09845
[endo]: https://www.nature.com/articles/s41598-019-51853-y
[UQ paper]: https://arxiv.org/abs/1909.05428
[obs-studies-journal]: https://obsstudies.org/277-2/
[obs-studies-arXiv]: https://arxiv.org/abs/1907.07592
[model projections]: https://arxiv.org/abs/1905.07103
[causal dss]: http://arxiv.org/abs/2001.07256
[saFAB paper]: https://arxiv.org/abs/1810.11042
[saFAB biometrika]: https://academic.oup.com/biomet/article-abstract/109/1/1/6154858
[PNAS thyroid]: https://doi.org/10.1073/pnas.1911333116
[saFABcode]: https://github.com/spencerwoody/safab-code
[ASTRAL code]: https://github.com/spencerwoody/ghost
[foxpnas]: https://www.pnas.org/doi/abs/10.1073/pnas.2111870119
